server:
  port: 8080

spring:
  application:
    name: notification-service
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use_sql_comments: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

data:
  kafka:
    topicName: kafka-mentoring
    bootstrapServerUrl: localhost:9092
    groupId: notification-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    enabled: false